### ISSUE TITLE
Install Issue

### ISSUE THREAD

**Issue by hoochiemama** [Viralmaniar/XposedOrNot#1]
ERROR: Command errored out with exit status 1:
     command: /usr/bin/python3 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-7fc294_z/hashlib/setup.py'"'"'; __file__='"'"'/tmp/pip-install-7fc294_z/hashlib/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-install-7fc294_z/hashlib/pip-egg-info
         cwd: /tmp/pip-install-7fc294_z/hashlib/
    Complete output (62 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/home/user1/.local/lib/python3.6/site-packages/setuptools/__init__.py", line 18, in <module>
        import setuptools.version
      File "/home/user1/.local/lib/python3.6/site-packages/setuptools/version.py", line 1, in <module>
        import pkg_resources
      File "/home/user1/.local/lib/python3.6/site-packages/pkg_resources/__init__.py", line 36, in <module>
        import email.parser
      File "/usr/lib/python3.6/email/parser.py", line 12, in <module>
        from email.feedparser import FeedParser, BytesFeedParser
      File "/usr/lib/python3.6/email/feedparser.py", line 27, in <module>
        from email._policybase import compat32
      File "/usr/lib/python3.6/email/_policybase.py", line 9, in <module>
        from email.utils import _has_surrogates
      File "/usr/lib/python3.6/email/utils.py", line 28, in <module>
        import random
      File "/usr/lib/python3.6/random.py", line 46, in <module>
        from hashlib import sha512 as _sha512
      File "/tmp/pip-install-7fc294_z/hashlib/hashlib.py", line 80
        raise ValueError, "unsupported hash type"
                        ^
    SyntaxError: invalid syntax
    Error in sys.excepthook:
    Traceback (most recent call last):
      File "/usr/lib/python3/dist-packages/apport_python_hook.py", line 63, in apport_excepthook
        from apport.fileutils import likely_packaged, get_recent_crashes
      File "/usr/lib/python3/dist-packages/apport/__init__.py", line 5, in <module>
        from apport.report import Report
      File "/usr/lib/python3/dist-packages/apport/report.py", line 12, in <module>
        import subprocess, tempfile, os.path, re, pwd, grp, os, time
      File "/usr/lib/python3.6/tempfile.py", line 184, in <module>
        from random import Random as _Random
      File "/usr/lib/python3.6/random.py", line 46, in <module>
        from hashlib import sha512 as _sha512
      File "/tmp/pip-install-7fc294_z/hashlib/hashlib.py", line 80
        raise ValueError, "unsupported hash type"
                        ^
    SyntaxError: invalid syntax

    Original exception was:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/home/user1/.local/lib/python3.6/site-packages/setuptools/__init__.py", line 18, in <module>
        import setuptools.version
      File "/home/user1/.local/lib/python3.6/site-packages/setuptools/version.py", line 1, in <module>
        import pkg_resources
      File "/home/user1/.local/lib/python3.6/site-packages/pkg_resources/__init__.py", line 36, in <module>
        import email.parser
      File "/usr/lib/python3.6/email/parser.py", line 12, in <module>
        from email.feedparser import FeedParser, BytesFeedParser
      File "/usr/lib/python3.6/email/feedparser.py", line 27, in <module>
        from email._policybase import compat32
      File "/usr/lib/python3.6/email/_policybase.py", line 9, in <module>
        from email.utils import _has_surrogates
      File "/usr/lib/python3.6/email/utils.py", line 28, in <module>
        import random
      File "/usr/lib/python3.6/random.py", line 46, in <module>
        from hashlib import sha512 as _sha512
      File "/tmp/pip-install-7fc294_z/hashlib/hashlib.py", line 80
        raise ValueError, "unsupported hash type"
                        ^
    SyntaxError: invalid syntax
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.

**Comment by carlosnewmusic** [comment]
![image](https://user-images.githubusercontent.com/19379457/72211914-accbc280-34d3-11ea-8fe2-f4e4be716659.png)

**Comment by ArkaineHeinlein** [comment]
Hi,

Do this:

easy_install hashlib
